# Generated by Django 5.0.1 on 2024-01-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademap', '0003_alter_jobpostings_profession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='contact',
            field=models.CharField(default=None, max_length=14),
            preserve_default=False,
        ),
    ]
