# Generated by Django 5.0.1 on 2024-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademap', '0004_jobpostings_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
